from __future__ import annotations

from app.schemas.bush import (
    BushBase,
    BushCreate,
    BushDetailResponse,
    BushDetails,
    BushListItem,
    BushRead,
    BushResponse,
    BushShort,
    BushStateUpdate,
    BushUpdate,
)
from app.schemas.closing import (
    ClosingBase,
    ClosingCash,
    ClosingCashUpdate,
    ClosingCreate,
    ClosingDeadlineAlert,
    ClosingDeadlineMissed,
    ClosingDetailResponse,
    ClosingDetails,
    ClosingGroupMessage,
    ClosingListItem,
    ClosingManualConfirm,
    ClosingRead,
    ClosingReceipt,
    ClosingReceiptUpdate,
    ClosingReportSchema,
    ClosingResponse,
    ClosingShort,
    ClosingSubmit,
    ClosingSummary,
    ClosingSummaryItem,
)
from app.schemas.cluster import (
    ClusterBase,
    ClusterCreate,
    ClusterDeadlineInfo,
    ClusterDetailResponse,
    ClusterDetails,
    ClusterListItem,
    ClusterRead,
    ClusterResponse,
    ClusterShort,
    ClusterStateUpdate,
    ClusterUpdate,
)
from app.schemas.common import (
    ActionResult,
    ActiveStateSchema,
    DateRange,
    DateTimeRange,
    EntityIdSchema,
    ErrorResponse,
    IdSchema,
    MessageResponse,
    OptionalReasonSchema,
    PaginatedResponse,
    PaginationMeta,
    PaginationParams,
    ReasonSchema,
    SchemaBase,
    SearchParams,
    SuccessResponse,
    TelegramMessageReference,
    TelegramUserReference,
    TimestampSchema,
)
from app.schemas.invite import (
    BushInviteCreate,
    DirectorInviteCreate,
    InviteActivate,
    InviteActivationResponse,
    InviteActivationResultSchema,
    InviteBase,
    InviteCreate,
    InviteCreated,
    InviteCreationResponse,
    InviteDetailResponse,
    InviteDetails,
    InviteInspectRequest,
    InviteInspectResponse,
    InviteListFilter,
    InviteListItem,
    InvitePayloadSchema,
    InviteRead,
    InviteResponse,
    InviteRevoke,
    InviteRevokeResponse,
    InviteRevocationResultSchema,
    InviteShort,
    StoreInviteCreate,
)
from app.schemas.opening import (
    OpeningAlertUpdate,
    OpeningBase,
    OpeningCheckinSchema,
    OpeningConfirm,
    OpeningConfirmationResponse,
    OpeningCreate,
    OpeningDeadlineItem,
    OpeningDeadlineMissed,
    OpeningDeadlineResponse,
    OpeningDetailResponse,
    OpeningDetails,
    OpeningLatenessInfo,
    OpeningListItem,
    OpeningManualUpdate,
    OpeningPreparationResponse,
    OpeningRead,
    OpeningResponse,
    OpeningShort,
    OpeningStatusUpdate,
    OpeningSummary,
    OpeningSummaryItem,
)
from app.schemas.report import (
    DailyReport,
    DailyReportSchema,
    DailyReportTotals,
    DailyReportTotalsSchema,
    ExcelReportDataSchema,
    ExcelReportSchema,
    ExcelSheetDataSchema,
    ExcelSheetSchema,
    PeriodReport,
    PeriodReportSchema,
    PeriodReportTotals,
    PeriodReportTotalsSchema,
    ReportExportRequest,
    ReportFileSchema,
    ReportPeriodSchema,
    ReportRequest,
    ReportSchemaBase,
    ReportScope,
    ReportScopeSchema,
    StoreDailyReportRow,
    StoreDailyReportRowSchema,
    StorePeriodSummary,
    StorePeriodSummarySchema,
    TelegramReportRequest,
)
from app.schemas.schedule import (
    ClusterAssignmentResultSchema,
    ClusterAssignmentSchema,
    EffectiveSchedule,
    EffectiveScheduleSchema,
    ScheduleDeletionResultSchema,
    ScheduleDeletionSchema,
    ScheduleExceptionBase,
    ScheduleExceptionChangeResultSchema,
    ScheduleExceptionChangeSchema,
    ScheduleExceptionCreate,
    ScheduleExceptionRead,
    ScheduleExceptionSchema,
    ScheduleExceptionStateUpdate,
    ScheduleExceptionUpdate,
    SchedulePreviewItem,
    SchedulePreviewItemSchema,
    SchedulePreviewSchema,
    ScheduleSchemaBase,
    StoreDayOffSet,
    StoreScheduleBase,
    StoreScheduleCopy,
    StoreScheduleCreate,
    StoreScheduleRead,
    StoreScheduleSchema,
    StoreScheduleUpdate,
    StoreWorkingDaySet,
    WeekdayScheduleChangeResultSchema,
    WeekdayScheduleChangeSchema,
    WEEKDAY_NAMES,
    WeeklySchedule,
    WeeklyScheduleCreate,
    weekday_name,
)
from app.schemas.store import (
    StoreBase,
    StoreBindingInfo,
    StoreBushUpdate,
    StoreClusterUpdate,
    StoreCreate,
    StoreDetailResponse,
    StoreDetails,
    StoreImportPreviewItem,
    StoreImportResult,
    StoreListItem,
    StoreRead,
    StoreResponse,
    StoreSelectItem,
    StoreShort,
    StoreStateUpdate,
    StoreUpdate,
)
from app.schemas.user import (
    TelegramProfileSchema,
    UserAccess,
    UserAccessSchema,
    UserActivityUpdate,
    UserAdminDashboard,
    UserBlock,
    UserCreate,
    UserDetailResponse,
    UserDetails,
    UserListItem,
    UserListItemSchema,
    UserPhoneUpdate,
    UserProfile,
    UserProfileUpdate,
    UserRead,
    UserResponse,
    UserRoleUpdate,
    UserSchemaBase,
    UserSearch,
    UserShort,
    UserStatistics,
    UserStatusUpdate,
    UserUnblock,
)


__all__ = [
    # =====================================================
    # COMMON
    # =====================================================
    "SchemaBase",
    "IdSchema",
    "EntityIdSchema",
    "MessageResponse",
    "SuccessResponse",
    "ErrorResponse",
    "ActionResult",
    "PaginationParams",
    "PaginationMeta",
    "PaginatedResponse",
    "DateRange",
    "DateTimeRange",
    "ReasonSchema",
    "OptionalReasonSchema",
    "ActiveStateSchema",
    "TelegramUserReference",
    "TelegramMessageReference",
    "TimestampSchema",
    "SearchParams",

    # =====================================================
    # BUSH
    # =====================================================
    "BushBase",
    "BushCreate",
    "BushUpdate",
    "BushRead",
    "BushDetails",
    "BushShort",
    "BushStateUpdate",
    "BushResponse",
    "BushDetailResponse",
    "BushListItem",

    # =====================================================
    # CLOSING
    # =====================================================
    "ClosingBase",
    "ClosingCreate",
    "ClosingReceipt",
    "ClosingCash",
    "ClosingSubmit",
    "ClosingGroupMessage",
    "ClosingDeadlineMissed",
    "ClosingDeadlineAlert",
    "ClosingCashUpdate",
    "ClosingReceiptUpdate",
    "ClosingManualConfirm",
    "ClosingRead",
    "ClosingDetails",
    "ClosingShort",
    "ClosingSummaryItem",
    "ClosingSummary",
    "ClosingResponse",
    "ClosingDetailResponse",
    "ClosingListItem",
    "ClosingReportSchema",

    # =====================================================
    # CLUSTER
    # =====================================================
    "ClusterBase",
    "ClusterCreate",
    "ClusterUpdate",
    "ClusterRead",
    "ClusterShort",
    "ClusterDetails",
    "ClusterDeadlineInfo",
    "ClusterStateUpdate",
    "ClusterResponse",
    "ClusterDetailResponse",
    "ClusterListItem",

    # =====================================================
    # INVITE
    # =====================================================
    "InviteBase",
    "StoreInviteCreate",
    "BushInviteCreate",
    "DirectorInviteCreate",
    "InviteCreate",
    "InviteCreated",
    "InvitePayloadSchema",
    "InviteActivate",
    "InviteActivationResponse",
    "InviteInspectRequest",
    "InviteInspectResponse",
    "InviteRevoke",
    "InviteRevokeResponse",
    "InviteRead",
    "InviteShort",
    "InviteDetails",
    "InviteListFilter",
    "InviteResponse",
    "InviteDetailResponse",
    "InviteListItem",
    "InviteCreationResponse",
    "InviteActivationResultSchema",
    "InviteRevocationResultSchema",

    # =====================================================
    # OPENING
    # =====================================================
    "OpeningBase",
    "OpeningCreate",
    "OpeningConfirm",
    "OpeningDeadlineMissed",
    "OpeningAlertUpdate",
    "OpeningManualUpdate",
    "OpeningStatusUpdate",
    "OpeningRead",
    "OpeningShort",
    "OpeningDetails",
    "OpeningPreparationResponse",
    "OpeningConfirmationResponse",
    "OpeningDeadlineItem",
    "OpeningDeadlineResponse",
    "OpeningSummaryItem",
    "OpeningSummary",
    "OpeningLatenessInfo",
    "OpeningResponse",
    "OpeningDetailResponse",
    "OpeningListItem",
    "OpeningCheckinSchema",

    # =====================================================
    # REPORT
    # =====================================================
    "ReportSchemaBase",
    "ReportScopeSchema",
    "ReportPeriodSchema",
    "ReportRequest",
    "StoreDailyReportRowSchema",
    "DailyReportTotalsSchema",
    "DailyReportSchema",
    "StorePeriodSummarySchema",
    "PeriodReportTotalsSchema",
    "PeriodReportSchema",
    "ExcelSheetDataSchema",
    "ExcelReportDataSchema",
    "TelegramReportRequest",
    "ReportExportRequest",
    "ReportFileSchema",
    "ReportScope",
    "DailyReport",
    "DailyReportTotals",
    "StoreDailyReportRow",
    "StorePeriodSummary",
    "PeriodReportTotals",
    "PeriodReport",
    "ExcelSheetSchema",
    "ExcelReportSchema",

    # =====================================================
    # SCHEDULE
    # =====================================================
    "WEEKDAY_NAMES",
    "weekday_name",
    "ScheduleSchemaBase",
    "StoreScheduleBase",
    "StoreScheduleCreate",
    "StoreScheduleUpdate",
    "StoreWorkingDaySet",
    "StoreDayOffSet",
    "StoreScheduleCopy",
    "WeeklyScheduleCreate",
    "StoreScheduleRead",
    "WeeklySchedule",
    "ScheduleExceptionBase",
    "ScheduleExceptionCreate",
    "ScheduleExceptionUpdate",
    "ScheduleExceptionRead",
    "ScheduleExceptionStateUpdate",
    "EffectiveScheduleSchema",
    "SchedulePreviewItemSchema",
    "SchedulePreviewSchema",
    "WeekdayScheduleChangeSchema",
    "ScheduleExceptionChangeSchema",
    "ScheduleDeletionSchema",
    "ClusterAssignmentSchema",
    "StoreScheduleSchema",
    "ScheduleExceptionSchema",
    "EffectiveSchedule",
    "SchedulePreviewItem",
    "WeekdayScheduleChangeResultSchema",
    "ScheduleExceptionChangeResultSchema",
    "ScheduleDeletionResultSchema",
    "ClusterAssignmentResultSchema",

    # =====================================================
    # STORE
    # =====================================================
    "StoreBase",
    "StoreCreate",
    "StoreUpdate",
    "StoreStateUpdate",
    "StoreBushUpdate",
    "StoreClusterUpdate",
    "StoreRead",
    "StoreShort",
    "StoreDetails",
    "StoreSelectItem",
    "StoreBindingInfo",
    "StoreImportPreviewItem",
    "StoreImportResult",
    "StoreResponse",
    "StoreDetailResponse",
    "StoreListItem",

    # =====================================================
    # USER
    # =====================================================
    "UserSchemaBase",
    "TelegramProfileSchema",
    "UserCreate",
    "UserProfileUpdate",
    "UserRoleUpdate",
    "UserStatusUpdate",
    "UserBlock",
    "UserUnblock",
    "UserPhoneUpdate",
    "UserRead",
    "UserShort",
    "UserDetails",
    "UserAccessSchema",
    "UserListItem",
    "UserSearch",
    "UserStatistics",
    "UserAdminDashboard",
    "UserActivityUpdate",
    "UserResponse",
    "UserDetailResponse",
    "UserListItemSchema",
    "UserProfile",
    "UserAccess",
]